apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aiclideployments.aicli.karmalabs.local
spec:
  group: aicli.karmalabs.local
  scope: Namespaced
  names:
    plural: aiclideployments
    singular: aiclideployment
    kind: Aiclideployment
    shortNames:
    - ad
    - aiclideploy
    - aideploy
  versions:
  - name: v1
    served: true
    storage: true
    schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
