apiVersion: v1
kind: Namespace
metadata:
 name: ai
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: ai-privileged
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: default
  namespace: ai
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai
  namespace: ai
  labels:
    app: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
      - name: onprem
        image: quay.io/karmab/aicli:latest
        command: ["/bin/sh"]
        args: ["-c", "apk update ; apk add podman ; aicli create onprem ; while true; do sleep 10; done"]
        env:
        - name: AI_URL
          value: "http://127.0.0.1:8090"
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
 name: ai-api
 namespace: ai
spec:
 selector:
   app: ai
 ports:
 - name: api
   protocol: TCP
   port: 8090
   targetPort: 8090
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
 labels:
   name: ai
 name: ai-api
 namespace: ai
spec:
 port:
   targetPort: api
 to:
   kind: Service
   name: ai-api
---
apiVersion: v1
kind: Service
metadata:
 name: ai-web
 namespace: ai
spec:
 selector:
   app: ai
 ports:
 - name: web
   protocol: TCP
   port: 8080
   targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
 labels:
   name: ai
 name: ai-web
 namespace: ai
spec:
 port:
   targetPort: web
 to:
   kind: Service
   name: ai-web
