name: CI-Workflow

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  ci-workflow:
    name: CI workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Run lint script
        run: ./.github/linting.sh
        shell: bash
      - name: Run build script
        run: ./.github/build.sh
        shell: bash
      - name: Run release.sh
        run: ./.github/release.sh
        shell: bash
