name: CI

on: [push, pull_request]

jobs:
  run-workflow:
    name: CI workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Lint Code
        run: ./.github/linting.sh
        shell: bash
      - name: Build Container
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: ./.github/build.sh
        shell: bash
      - name: Push container
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: ./.github/release.sh
        shell: bash
        env:
         QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
         QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
         PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
         PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
