name: deploy-cluster

on:
  workflow_dispatch:
    inputs:
      CLUSTER:
        description: 'Cluster Name'
        required: true
        default: ci-ai
      NODES:
        description: 'Nodes'
        required: true
        default: 3
      PULLSECRET:
        description: 'Pull Secret'
        required: false
        default: /root/openshift_pull.json
      PARAMFILE:
        description: 'paramfile'
        required: false
        default: .github/aicli_parameters.yml

env:
 HOME: /root
 PYTHONUNBUFFERED: true
 CLUSTER: ${{github.event.inputs.CLUSTER}}
 NODES: ${{github.event.inputs.NODES}}
 PULLSECRET: ${{github.event.inputs.PULLSECRET}}
 PARAMFILE: ${{github.event.inputs.PARAMFILE}}
 AI_OFFLINETOKEN: ${{ secrets.AI_OFFLINETOKEN }}
# CLUSTER: ai-ci
# PULLSECRET: /root/openshift_pull.json
# PARAMFILE: .github/aicli_parameters.yml

jobs:
    requirements:
      runs-on: libvirt
      steps:
       - uses: actions/checkout@v2
       - run: git pull origin ${GITHUB_REF##*/}
       - name: Install kcli
         run: |
           curl https://raw.githubusercontent.com/karmab/kcli/master/install.sh | bash
       - name: Install aicli
         run: |
           pip3 install -U assisted-service-client
           python3 setup.py install
       - name: Clean up
         continue-on-error: true
         run: |
           kcli delete plan --yes $CLUSTER || true
           [ -f /var/lib/libvirt/images/$CLUSTER.iso ] && rm -rf /var/lib/libvirt/images/$CLUSTER.iso
           aicli delete cluster $CLUSTER || true

    deploy-ai-cluster:
      needs: requirements
      runs-on: libvirt
      steps:
      - name: Deploy ai cluster
        run: |
          DOWNLOAD_ISO_CMD="kcli create vm -P iso=$CLUSTER.iso -P disks=[200] -P memory=20480 -P numcpus=16 --count=$NODES $CLUSTER"
          aicli create deployment --pf $PARAMFILE -P pull_secret=$PULLSECRET -P download_iso_cmd="$DOWNLOAD_ISO_CMD" $CLUSTER
